import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Assignment: 11",
  description: "Generated by MHZ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="max-w-[1240px] m-auto justify-center">{children}</div>
      </body>
    </html>
  );
}
